"""Neutral shared layout helpers for active generation/runtime code."""

from app.services.layouts.layout_metadata import get_layout_metadata_entry, load_layout_metadata
from app.services.layouts.layout_roles import (
    LayoutRole,
    format_role_contract_for_prompt,
    get_default_layout_for_role,
    get_layout_role,
    get_layout_role_description,
    get_layout_role_label,
    get_outline_item_role,
    is_variant_pilot_role,
    normalize_outline_items_roles,
    normalize_slide_role,
)
from app.services.layouts.layout_taxonomy import (
    LayoutDesignTraits,
    LayoutGroup,
    LayoutTemplateNotes,
    LayoutTaxonomyEntry,
    LayoutVariantDefinition,
    get_design_trait_description,
    get_design_trait_label,
    get_group_order,
    get_layout_group_description,
    get_layout_group_label,
    get_layout_notes,
    get_layout_taxonomy,
    get_layout_variant_definition,
    get_sub_group_description,
    get_sub_group_label,
    get_sub_groups_for_group,
    get_variant_ids_for_sub_group,
)
from app.services.layouts.layout_usage import (
    format_usage_tags,
    get_layout_usage_tags,
    get_usage_label,
    infer_document_and_slide_usage,
    infer_usage_tags,
    rank_layouts_by_usage,
)

__all__ = [
    "LayoutDesignTraits",
    "LayoutGroup",
    "LayoutRole",
    "LayoutTaxonomyEntry",
    "LayoutTemplateNotes",
    "LayoutVariantDefinition",
    "format_role_contract_for_prompt",
    "format_usage_tags",
    "get_default_layout_for_role",
    "get_design_trait_description",
    "get_design_trait_label",
    "get_group_order",
    "get_layout_group_description",
    "get_layout_group_label",
    "get_layout_metadata_entry",
    "get_layout_notes",
    "get_layout_role",
    "get_layout_role_description",
    "get_layout_role_label",
    "get_layout_taxonomy",
    "get_layout_usage_tags",
    "get_layout_variant_definition",
    "get_outline_item_role",
    "get_sub_group_description",
    "get_sub_group_label",
    "get_sub_groups_for_group",
    "get_usage_label",
    "get_variant_ids_for_sub_group",
    "infer_document_and_slide_usage",
    "infer_usage_tags",
    "is_variant_pilot_role",
    "load_layout_metadata",
    "normalize_outline_items_roles",
    "normalize_slide_role",
    "rank_layouts_by_usage",
]
